import {
  Anchor,
  Award,
  Backpack,
  Bed,
  Bike,
  Binoculars,
  Bird,
  Briefcase,
  Building2,
  Bus,
  Camera,
  Car,
  Check,
  Clock,
  Coffee,
  Compass,
  Eye,
  FileText,
  Fish,
  Flower2,
  Footprints,
  Glasses,
  Globe,
  HandCoins,
  Heart,
  HeartPulse,
  Hotel,
  Landmark,
  Leaf,
  LifeBuoy,
  type LucideIcon,
  Map,
  Megaphone,
  MessagesSquare,
  Minus,
  Mountain,
  MountainSnow,
  Plane,
  Sailboat,
  Shield,
  ShieldCheck,
  Smile,
  Snowflake,
  Sparkles,
  Star,
  Sun,
  Sunrise,
  Tag,
  Tent,
  Ticket,
  TrainFront,
  TreePalm,
  UserCheck,
  Users,
  Utensils,
  Video,
  Wallet,
  Waves,
  Wind,
  Wrench,
  X,
} from 'lucide-react';

/** Curated Lucide icons (the same set used in the Figma file). Admins pick icons by these names. */
export const ICONS: Record<string, LucideIcon> = {
  anchor: Anchor,
  award: Award,
  backpack: Backpack,
  bed: Bed,
  bike: Bike,
  binoculars: Binoculars,
  bird: Bird,
  briefcase: Briefcase,
  'building-2': Building2,
  bus: Bus,
  camera: Camera,
  car: Car,
  check: Check,
  clock: Clock,
  coffee: Coffee,
  compass: Compass,
  eye: Eye,
  'file-text': FileText,
  fish: Fish,
  'flower-2': Flower2,
  footprints: Footprints,
  glasses: Glasses,
  globe: Globe,
  'hand-coins': HandCoins,
  heart: Heart,
  'heart-pulse': HeartPulse,
  hotel: Hotel,
  landmark: Landmark,
  leaf: Leaf,
  'life-buoy': LifeBuoy,
  map: Map,
  megaphone: Megaphone,
  'messages-square': MessagesSquare,
  minus: Minus,
  mountain: Mountain,
  'mountain-snow': MountainSnow,
  plane: Plane,
  sailboat: Sailboat,
  shield: Shield,
  'shield-check': ShieldCheck,
  smile: Smile,
  snowflake: Snowflake,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  sunrise: Sunrise,
  tag: Tag,
  tent: Tent,
  ticket: Ticket,
  'train-front': TrainFront,
  'tree-palm': TreePalm,
  'user-check': UserCheck,
  users: Users,
  utensils: Utensils,
  video: Video,
  wallet: Wallet,
  waves: Waves,
  wind: Wind,
  wrench: Wrench,
  x: X,
};

export const ICON_NAMES = Object.keys(ICONS).sort();

interface IconProps {
  name: string | null | undefined;
  size?: number;
  className?: string;
  strokeWidth?: number;
}

export function Icon({ name, size = 20, className, strokeWidth = 1.75 }: IconProps) {
  const Component = (name && ICONS[name]) || Compass;
  return <Component size={size} className={className} strokeWidth={strokeWidth} aria-hidden="true" />;
}
