import { u } from './taxonomy';
import type { SeedTrip } from './types';

const worldFaq = [
  { q: 'Are flights included?', a: 'International flights are not included so you can use your own miles or preferred airline. We are happy to recommend routings.' },
  { q: 'Can I travel on different dates?', a: 'Yes — every itinerary can run privately on the dates you choose, subject to hotel availability.' },
  { q: 'What happens if I need to cancel?', a: 'Our cancellation terms are explained before you pay anything. We strongly recommend travel insurance from the moment you book.' },
];

const trips = [
  {
    title: 'Dubai Desert Safari & City Stay',
    slug: 'dubai-desert-safari-city-stay',
    country: 'uae',
    location: 'Dubai',
    summary: 'Dune-bashing at sunset, a Bedouin-style camp under the stars and the best of Dubai’s skyline, souks and beaches.',
    overview:
      'Five days that balance adventure and comfort. Ride the red dunes of the Lahbab desert, sleep at a heritage camp and wake for a camel ride at sunrise before returning to the city for Old Dubai, the Burj Khalifa and a dhow dinner cruise.',
    priceFrom: 480, durationDays: 5, difficulty: 'Easy', groupSizeMax: 14, bestSeason: 'October–April',
    rating: 4.7, reviewCount: 62, isFeatured: true, activities: ['city-breaks', 'sunrise', 'wildlife-safari'],
    photos: [
      ['1612899326681-66508905b4ce', 'Tourists and a guide crossing Dubai desert dunes'],
      ['1549944850-84e00be4203b', 'Camels resting on desert sand'],
      ['1624062999726-083e5268525d', 'A 4x4 on the dunes'],
      ['1576159470850-494c8b17aca0', 'Safari vehicles in the desert'],
      ['1504326787394-e6d75cae8027', 'A couple walking in the desert'],
    ],
    highlights: ['Sunset dune drive and desert camp', 'Sunrise camel ride', 'Burj Khalifa observation deck', 'Dhow dinner cruise on Dubai Creek'],
    days: [
      [1, 'Arrive in Dubai', 'Private transfer to your Downtown hotel and a fountain show evening.', '', '', 'Hotel', ''],
      [2, 'Old Dubai and the souks', 'Al Fahidi district, abra ride across the creek, spice and gold souks.', '3 hrs', '', 'Hotel', 'Breakfast'],
      [3, 'Desert safari', 'Afternoon dune drive, falconry display and an overnight at a heritage desert camp.', '', '', 'Desert camp', 'B · D'],
      [4, 'Sunrise camel ride and Burj Khalifa', 'Camel trek at dawn, return to the city and sunset from level 124.', '2 hrs', '', 'Hotel', 'B · D'],
      [5, 'Departure', 'Beach morning at Kite Beach before your transfer.', '', '', '', 'Breakfast'],
    ],
    included: [['Private airport transfers', 'car'], ['Four nights accommodation', 'hotel'], ['Desert safari with camp dinner', 'tent'], ['Burj Khalifa tickets', 'ticket']],
    excluded: [['International flights', 'plane'], ['Tourism dirham fee', 'wallet']],
    departures: [['2026-10-15', 14, 8], ['2026-11-19', 14, 14], ['2027-01-14', 14, 11]],
  },
  {
    title: 'Lucerne & Jungfrau Alpine Break',
    slug: 'lucerne-jungfrau-alpine-break',
    country: 'switzerland',
    location: 'Lucerne & Bernese Oberland',
    summary: 'Lake cruises, glacier railways and flower-meadow walks in the most scenic corner of the Swiss Alps.',
    overview:
      'Base yourself in Lucerne and Grindelwald for a relaxed Alpine break. Cruise Lake Lucerne to Mount Pilatus, ride the cogwheel railway to Jungfraujoch — the “Top of Europe” — and walk gentle trails past waterfalls in the Lauterbrunnen valley.',
    priceFrom: 799, durationDays: 4, difficulty: 'Easy', groupSizeMax: 14, maxAltitude: 3454, bestSeason: 'June–September',
    rating: 4.8, reviewCount: 37, badge: 'Scenic rail', isFeatured: true, activities: ['trekking', 'city-breaks', 'swimming'],
    photos: [
      ['1586752488885-6ce47fdfd874', 'The Matterhorn above Zermatt'],
      ['1527668752968-14dc70a27c95', 'Spring in a Swiss Alpine village'],
      ['1521292270410-a8c4d716d518', 'Valley view towards the Top of Europe'],
      ['1593186344142-ef775a6e596f', 'A red mountain train below snowy peaks'],
      ['1607585011081-241d2bacb7de', 'A mountain town with snowy peaks behind'],
    ],
    highlights: ['Jungfraujoch glacier railway', 'Lake Lucerne cruise and Mount Pilatus', 'Lauterbrunnen waterfall valley walk'],
    days: [
      [1, 'Arrive in Lucerne', 'Chapel Bridge, the old town and a lakeside dinner.', '2 hrs', '435 m', 'Hotel', 'Dinner'],
      [2, 'Lake cruise and Mount Pilatus', 'Paddle steamer, the world’s steepest cogwheel railway and a cable car back down.', '2 hrs', '2,128 m', 'Hotel', 'Breakfast'],
      [3, 'Grindelwald and Jungfraujoch', 'Scenic train to the Top of Europe, ice palace and Sphinx observatory.', '2 hrs', '3,454 m', 'Chalet hotel', 'B · D'],
      [4, 'Lauterbrunnen and departure', 'Valley walk to Staubbach Falls before your onward train.', '3 hrs', '795 m', '', 'Breakfast'],
    ],
    included: [['Swiss Travel Pass for the trip', 'train-front'], ['Three nights hotel and chalet', 'hotel'], ['Jungfraujoch excursion', 'mountain-snow'], ['Lake cruise', 'sailboat']],
    excluded: [['Flights to Zurich', 'plane'], ['City tourist taxes', 'wallet']],
    departures: [['2027-06-10', 14, 14], ['2027-07-08', 14, 9]],
  },
  {
    title: 'Paris 6-Day Tour',
    slug: 'paris-6-day-tour',
    country: 'france',
    location: 'Paris',
    summary: 'The Eiffel Tower at sparkle hour, the Louvre with an art historian, Montmartre mornings and a day trip to Versailles.',
    overview:
      'A beautifully paced week in Paris staying in a boutique hotel in Saint-Germain. Skip-the-line visits and small-group walks leave plenty of time for cafés, markets and the simple pleasure of getting a little lost.',
    priceFrom: 989, durationDays: 6, difficulty: 'Easy', groupSizeMax: 12, bestSeason: 'April–June, Sept–Oct',
    rating: 4.8, reviewCount: 54, isFeatured: true, activities: ['city-breaks', 'cultural'],
    photos: [
      ['1502602898657-3e91760cbb34', 'The Eiffel Tower and Paris rooftops'],
      ['1431274172761-fca41d930114', 'The Eiffel Tower at dusk'],
      ['1583265266785-aab9e443ee68', 'The Eiffel Tower at sunset'],
      ['1553455427-c38fa28dc586', 'The Eiffel Tower from the gardens'],
      ['1569949380643-6e746ecaa3bd', 'Visitors near the Eiffel Tower'],
    ],
    highlights: ['Skip-the-line Louvre with an art historian', 'Seine cruise and Eiffel Tower summit', 'Palace and gardens of Versailles', 'Montmartre food walk'],
    days: [
      [1, 'Bienvenue à Paris', 'Check in, orientation walk and a welcome dinner in a classic bistro.', '2 hrs', '', 'Boutique hotel', 'Dinner'],
      [2, 'The Louvre and Île de la Cité', 'Morning at the Louvre, afternoon at Notre-Dame and Sainte-Chapelle.', '4 hrs', '', 'Boutique hotel', 'Breakfast'],
      [3, 'Versailles', 'Palace, Hall of Mirrors and bikes through the gardens.', '4 hrs', '', 'Boutique hotel', 'Breakfast'],
      [4, 'Montmartre and Seine cruise', 'Food walk in the artists’ quarter and an evening cruise.', '3 hrs', '', 'Boutique hotel', 'B · L'],
      [5, 'Eiffel Tower and Musée d’Orsay', 'Summit visit, Impressionists and a farewell dinner.', '3 hrs', '', 'Boutique hotel', 'B · D'],
      [6, 'Au revoir', 'Free morning and transfer.', '', '', '', 'Breakfast'],
    ],
    included: [['Five nights boutique hotel', 'hotel'], ['Museum and palace tickets', 'ticket'], ['Local expert guides', 'user-check'], ['Seine river cruise', 'sailboat']],
    excluded: [['International flights', 'plane'], ['City tax', 'wallet']],
    departures: [['2026-10-06', 12, 4], ['2027-04-13', 12, 12], ['2027-05-18', 12, 10]],
  },
  {
    title: 'Golden Triangle & Taj Mahal Sunrise',
    slug: 'golden-triangle-taj-mahal-sunrise',
    country: 'india',
    location: 'Delhi · Agra · Jaipur',
    summary: 'Old Delhi’s lanes, the Taj Mahal at first light and the pink city of Jaipur in one colourful week.',
    overview:
      'India’s classic introduction. Rickshaw through Chandni Chowk, watch sunrise at the Taj Mahal, stop at the abandoned city of Fatehpur Sikri and explore Jaipur’s Amber Fort and bazaars with a local guide.',
    priceFrom: 720, durationDays: 6, difficulty: 'Easy', groupSizeMax: 14, bestSeason: 'October–March',
    rating: 4.7, reviewCount: 48, isFeatured: true, activities: ['cultural', 'sunrise', 'city-breaks'],
    photos: [
      ['1564507592333-c60657eea523', 'The Taj Mahal and its reflecting pool'],
      ['1587135941948-670b381f08ce', 'The Taj Mahal at golden hour'],
      ['1548013146-72479768bada', 'Visitors in front of the Taj Mahal'],
      ['1523980145253-50327d891e0e', 'The Taj Mahal, Agra'],
      ['1567255097545-018d2b9c414c', 'A quiet view of the Taj Mahal'],
    ],
    highlights: ['Sunrise at the Taj Mahal', 'Rickshaw ride in Old Delhi', 'Amber Fort and Jaipur’s bazaars'],
    days: [
      [1, 'Arrive in Delhi', 'Transfer to your hotel; evening at Humayun’s Tomb.', '', '', 'Hotel', 'Dinner'],
      [2, 'Old and New Delhi', 'Jama Masjid, Chandni Chowk by rickshaw, India Gate and Qutub Minar.', '4 hrs', '', 'Hotel', 'Breakfast'],
      [3, 'Drive to Agra', 'Agra Fort and sunset over the Taj from Mehtab Bagh.', '2 hrs', '', 'Hotel', 'B · D'],
      [4, 'Taj Mahal sunrise, drive to Jaipur', 'The Taj at dawn, then Fatehpur Sikri on the road to Jaipur.', '3 hrs', '', 'Heritage haveli', 'B · D'],
      [5, 'Jaipur', 'Amber Fort, City Palace, Hawa Mahal and a block-printing workshop.', '4 hrs', '', 'Heritage haveli', 'Breakfast'],
      [6, 'Return to Delhi and depart', 'Drive back for evening flights.', '', '', '', 'Breakfast'],
    ],
    included: [['Private air-conditioned vehicle', 'car'], ['Five nights hotels and haveli', 'hotel'], ['Monument entry fees', 'ticket'], ['English-speaking guides', 'user-check']],
    excluded: [['India e-Visa', 'file-text'], ['International flights', 'plane']],
    departures: [['2026-10-20', 14, 10], ['2026-12-01', 14, 14], ['2027-02-02', 14, 8]],
  },
  {
    title: 'Bhutan: Tiger’s Nest & Thimphu Journey',
    slug: 'bhutan-tigers-nest-thimphu',
    country: 'bhutan',
    location: 'Paro · Thimphu · Punakha',
    summary: 'Hike to the cliffside Tiger’s Nest monastery, cross prayer-flag passes and meet the monks of Punakha Dzong.',
    overview:
      'Bhutan protects its culture and landscapes like nowhere else. This journey pairs gentle hikes with fortress-monasteries, farmhouse lunches and time with local guides who are proud to share the “Land of the Thunder Dragon”.',
    priceFrom: 1850, durationDays: 6, difficulty: 'Moderate', groupSizeMax: 10, maxAltitude: 3120, bestSeason: 'Mar–May, Sep–Nov',
    rating: 4.9, reviewCount: 22, badge: 'Rare find', isFeatured: false, activities: ['cultural', 'trekking', 'pilgrimage'],
    photos: [
      ['1700040005384-1fc87f522053', 'The Tiger’s Nest temple on the cliff, Bhutan'],
      ['1644495949450-9a0fe21b7376', 'Paro Taktsang monastery'],
      ['1584003734930-b12779f66351', 'Tashichho Dzong in Thimphu'],
      ['1599025740240-fb3e25f59932', 'Travellers walking a Bhutanese trail'],
      ['1729180253317-93ba9cf4ceb4', 'A monastery above the valley'],
    ],
    highlights: ['Hike to Paro Taktsang (Tiger’s Nest)', 'Dochula Pass and its 108 chortens', 'Punakha Dzong at the river confluence'],
    days: [
      [1, 'Fly into Paro', 'One of the world’s most dramatic landings, then Paro Rinpung Dzong.', '1 hr', '2,200 m', 'Hotel', 'L · D'],
      [2, 'Thimphu', 'Buddha Dordenma, the weekend market and Tashichho Dzong.', '2 hrs', '2,334 m', 'Hotel', 'B · L · D'],
      [3, 'Over Dochula to Punakha', 'Prayer-flag pass, farmhouse lunch and Punakha Dzong.', '2 hrs', '1,200 m', 'Lodge', 'B · L · D'],
      [4, 'Punakha valley walk', 'Suspension bridge, rice fields and the Chimi Lhakhang temple.', '3 hrs', '1,300 m', 'Lodge', 'B · L · D'],
      [5, 'Tiger’s Nest hike', 'The iconic climb to Paro Taktsang and a hot-stone bath in the evening.', '5–6 hrs', '3,120 m', 'Hotel', 'B · L · D'],
      [6, 'Departure', 'Morning flight from Paro.', '', '2,200 m', '', 'Breakfast'],
    ],
    included: [['Bhutan visa and Sustainable Development Fee', 'file-text'], ['Licensed Bhutanese guide and driver', 'user-check'], ['All meals and accommodation', 'bed'], ['Monument entry fees', 'ticket']],
    excluded: [['Flights to Paro', 'plane'], ['Tips', 'hand-coins']],
    departures: [['2026-10-22', 10, 3], ['2027-04-08', 10, 10]],
  },
  {
    title: 'Maldives Snorkel & Island Escape',
    slug: 'maldives-snorkel-island-escape',
    country: 'maldives',
    location: 'South Ari Atoll',
    summary: 'House-reef snorkelling, a whale-shark excursion and sandbank picnics in a laid-back island resort.',
    overview:
      'Swap schedules for sea turtles. Stay on a coral island in South Ari Atoll — famous for year-round whale sharks — with daily snorkelling, a sunset dolphin cruise and optional try-dive with a PADI instructor.',
    priceFrom: 1290, durationDays: 5, difficulty: 'Easy', groupSizeMax: 12, bestSeason: 'November–April',
    rating: 4.8, reviewCount: 31, isFeatured: false, activities: ['swimming', 'diving', 'wildlife-safari'],
    photos: [
      ['1674718275085-3c3f30dabcd1', 'A turtle swimming in clear Maldivian water'],
      ['1706753459618-31e52d7ca22d', 'Snorkelling in the Maldives'],
      ['1618266089457-8cbed84e2e53', 'A whale shark in South Ari Atoll'],
      ['1674718246692-19a7c2c39462', 'Coral and anemone underwater'],
      ['1594155698660-b9a8b367d86d', 'A swimmer in crystal-clear water'],
    ],
    highlights: ['Whale-shark snorkel excursion', 'Sunset dolphin cruise', 'Private sandbank picnic'],
    days: [
      [1, 'Seaplane to the atoll', 'Arrive in Malé and fly low over the lagoons to your island.', '', '', 'Beach villa', 'Dinner'],
      [2, 'House reef and turtles', 'Guided snorkel with a marine biologist.', '2 hrs', '', 'Beach villa', 'B · D'],
      [3, 'Whale sharks', 'Half-day boat trip to find the gentle giants.', '4 hrs', '', 'Beach villa', 'B · L · D'],
      [4, 'Sandbank and dolphins', 'Picnic on a private sandbank and a sunset dolphin cruise.', '', '', 'Beach villa', 'B · L · D'],
      [5, 'Departure', 'Morning swim and seaplane back to Malé.', '', '', '', 'Breakfast'],
    ],
    included: [['Return seaplane transfers', 'plane'], ['Four nights beach villa, half board', 'hotel'], ['Guided snorkel excursions', 'fish'], ['Snorkel equipment', 'glasses']],
    excluded: [['International flights', 'plane'], ['Diving courses', 'fish']],
    departures: [['2026-12-05', 12, 6], ['2027-02-06', 12, 12]],
  },
  {
    title: 'Bali Rice Terraces & Temples',
    slug: 'bali-rice-terraces-temples',
    country: 'indonesia',
    location: 'Ubud · Sidemen · Uluwatu',
    summary: 'Cycle through emerald rice terraces, join a temple blessing and swim below hidden waterfalls.',
    overview:
      'Discover the Bali beyond the beach clubs. Stay in Ubud’s jungle, cycle downhill through Tegallalang’s rice terraces, climb Mount Batur for sunrise and end with cliff-top temples and a Kecak fire dance at Uluwatu.',
    priceFrom: 940, durationDays: 7, difficulty: 'Moderate', groupSizeMax: 12, maxAltitude: 1717, bestSeason: 'April–October',
    rating: 4.7, reviewCount: 45, isFeatured: true, activities: ['cultural', 'cycling', 'swimming', 'sunrise'],
    photos: [
      ['1555400038-63f5ba517a47', 'Tegallalang rice terraces in Bali'],
      ['1513415756790-2ac1db1297d0', 'Aerial view of rice terraces'],
      ['1715755455989-76413081ad10', 'A lush hillside of terraces'],
      ['1633820313053-fa030b13ef94', 'Rice fields and palm trees'],
      ['1608335715837-1994a535d5c3', 'Sunrise over Balinese rice fields'],
    ],
    highlights: ['Mount Batur sunrise trek', 'Downhill rice-terrace bike ride', 'Water temple blessing at Tirta Empul', 'Kecak fire dance at Uluwatu'],
    days: [
      [1, 'Arrive in Ubud', 'Transfer to a jungle-view hotel and welcome dinner.', '', '', 'Hotel', 'Dinner'],
      [2, 'Rice terraces by bike', 'Downhill ride through villages and the Tegallalang terraces.', '3 hrs', '', 'Hotel', 'B · L'],
      [3, 'Mount Batur sunrise', 'Pre-dawn trek to the crater rim and a natural hot spring.', '4 hrs', '1,717 m', 'Hotel', 'B · L'],
      [4, 'Temples and waterfalls', 'Tirta Empul blessing and a swim at Tukad Cepung waterfall.', '2 hrs', '', 'Hotel', 'Breakfast'],
      [5, 'Sidemen valley', 'Weaving villages and a cooking class.', '2 hrs', '', 'Villa', 'B · L'],
      [6, 'Uluwatu', 'Cliff-top temple and Kecak fire dance at sunset.', '1 hr', '', 'Resort', 'B · D'],
      [7, 'Departure', 'Beach morning before your transfer.', '', '', '', 'Breakfast'],
    ],
    included: [['Six nights hotels and villa', 'hotel'], ['Bike tour and Batur trek', 'bike'], ['Temple entries and sarong hire', 'ticket'], ['Private driver-guide', 'car']],
    excluded: [['Bali tourist levy', 'wallet'], ['International flights', 'plane']],
    departures: [['2027-04-20', 12, 12], ['2027-06-15', 12, 7]],
  },
  {
    title: 'Machu Picchu & Sacred Valley',
    slug: 'machu-picchu-sacred-valley',
    country: 'peru',
    location: 'Cusco · Sacred Valley',
    summary: 'Andean markets, Inca terraces and a sunrise entry to Machu Picchu with an archaeologist guide.',
    overview:
      'Acclimatise gently in the Sacred Valley before exploring Cusco’s colonial streets and taking the scenic Vistadome train to Aguas Calientes. A two-day Machu Picchu visit includes the Sun Gate walk and an early entry before the crowds.',
    priceFrom: 1690, durationDays: 8, difficulty: 'Moderate', groupSizeMax: 12, maxAltitude: 3399, bestSeason: 'May–September',
    rating: 4.9, reviewCount: 27, isFeatured: false, activities: ['trekking', 'cultural', 'sunrise'],
    photos: [
      ['1567597243073-2d274aabecec', 'Machu Picchu ruins framed by a stone window'],
      ['1664387518989-bb1d8574f078', 'Llamas above Machu Picchu'],
      ['1509216242873-7786f446f465', 'Aerial view of green Andean peaks'],
      ['1530999811698-221aa9eb1739', 'Machu Picchu at dawn from the viewpoint'],
    ],
    highlights: ['Sunrise entry to Machu Picchu', 'Pisac market and Ollantaytambo fortress', 'Vistadome train through the Urubamba gorge'],
    days: [
      [1, 'Arrive in Cusco, descend to the Sacred Valley', 'Rest at lower altitude to acclimatise.', '', '2,870 m', 'Hacienda', 'Dinner'],
      [2, 'Pisac and weaving village', 'Market, terraces and a Quechua weaving demonstration.', '3 hrs', '2,970 m', 'Hacienda', 'B · L'],
      [3, 'Ollantaytambo', 'Inca fortress and a living Inca town.', '2 hrs', '2,792 m', 'Hacienda', 'B · D'],
      [4, 'Train to Machu Picchu', 'Vistadome train and an afternoon visit to the citadel.', '3 hrs', '2,430 m', 'Hotel', 'B · D'],
      [5, 'Sunrise and the Sun Gate', 'Early entry and a walk to Inti Punku; train to Cusco.', '4 hrs', '2,720 m', 'Hotel', 'Breakfast'],
      [6, 'Cusco', 'Qoricancha, San Pedro market and Sacsayhuamán.', '3 hrs', '3,399 m', 'Hotel', 'Breakfast'],
      [7, 'Rainbow of flavours', 'Free morning and a Peruvian cooking class.', '', '3,399 m', 'Hotel', 'B · L'],
      [8, 'Departure', 'Transfer to Cusco airport.', '', '3,399 m', '', 'Breakfast'],
    ],
    included: [['Machu Picchu entry and guide', 'ticket'], ['Vistadome train', 'train-front'], ['Seven nights hotels', 'hotel'], ['All transfers', 'car']],
    excluded: [['Flights to Cusco', 'plane'], ['Travel insurance', 'shield']],
    departures: [['2027-05-11', 12, 12], ['2027-07-06', 12, 5]],
  },
  {
    title: 'Serengeti Balloon Safari',
    slug: 'serengeti-balloon-safari',
    country: 'tanzania',
    location: 'Serengeti · Ngorongoro',
    summary: 'Game drives with expert guides, the Ngorongoro Crater and a champagne balloon flight over the plains at dawn.',
    overview:
      'Follow the Great Migration across the Serengeti, descend into the wildlife-packed Ngorongoro Crater and float silently above the savanna at sunrise. Stays in comfortable tented camps put you close to the action.',
    priceFrom: 2450, durationDays: 7, difficulty: 'Easy', groupSizeMax: 6, bestSeason: 'June–October',
    rating: 4.9, reviewCount: 18, badge: 'Once in a lifetime', isFeatured: false, activities: ['wildlife-safari', 'sunrise'],
    photos: [
      ['1717863827284-1360456b99db', 'Wildebeest on the plains of Tanzania'],
      ['1617415420840-48518720fe26', 'A hot air balloon taking off at sunrise'],
      ['1617415414949-a4c30d8ecb0b', 'A balloon rising into the morning sky'],
      ['1721739179949-2179fbdf295e', 'A balloon drifting over water'],
    ],
    highlights: ['Sunrise balloon flight with bush breakfast', 'Full day in the Ngorongoro Crater', 'Migration game drives in a 6-seat vehicle'],
    days: [
      [1, 'Arrive in Arusha', 'Garden lodge welcome and safari briefing.', '', '1,400 m', 'Lodge', 'Dinner'],
      [2, 'Tarangire National Park', 'Elephants and baobabs on your first game drive.', '6 hrs', '', 'Tented camp', 'B · L · D'],
      [3, 'Into the Serengeti', 'Drive through the highlands to the central plains.', '7 hrs', '', 'Tented camp', 'B · L · D'],
      [4, 'Balloon flight', 'Dawn flight, bush breakfast and afternoon game drive.', '', '', 'Tented camp', 'B · L · D'],
      [5, 'Serengeti game drives', 'Full day tracking big cats and the herds.', '8 hrs', '', 'Tented camp', 'B · L · D'],
      [6, 'Ngorongoro Crater', 'Descend into the caldera for rhino and lion.', '7 hrs', '2,300 m', 'Crater lodge', 'B · L · D'],
      [7, 'Departure', 'Return to Arusha for your flight.', '', '1,400 m', '', 'Breakfast'],
    ],
    included: [['Private 4x4 with pop-up roof', 'car'], ['Park and crater fees', 'shield-check'], ['Balloon flight', 'wind'], ['Full-board tented camps', 'tent']],
    excluded: [['Tanzania e-Visa', 'file-text'], ['International flights', 'plane'], ['Tips for guides', 'hand-coins']],
    departures: [['2027-07-14', 6, 6], ['2027-08-11', 6, 2]],
  },
  {
    title: 'New York City Break',
    slug: 'new-york-city-break',
    country: 'usa',
    location: 'New York',
    summary: 'Skyline views, Broadway nights, Central Park by bike and the neighbourhoods locals love.',
    overview:
      'Five energetic days in the city that never sleeps. Stay in Midtown, cycle Central Park, walk the Brooklyn Bridge at golden hour, catch a Broadway show and eat your way through Chinatown and Greenwich Village.',
    priceFrom: 1150, durationDays: 5, difficulty: 'Easy', groupSizeMax: 14, bestSeason: 'April–June, Sept–Dec',
    rating: 4.6, reviewCount: 39, isFeatured: false, activities: ['city-breaks', 'cycling', 'cultural'],
    photos: [
      ['1485871981521-5b1fd3805eee', 'The Empire State Building at sunset'],
      ['1496588152823-86ff7695e68f', 'Brooklyn Bridge and Manhattan'],
      ['1499092346589-b9b6be3e94b2', 'Manhattan skyline across the East River'],
      ['1496442226666-8d4d0e62e6e9', 'Times Square at Manhattanhenge'],
      ['1568515387631-8b650bbcdb90', 'Central Park in New York'],
    ],
    highlights: ['Broadway show tickets', 'Central Park bike tour', 'Top of the Rock at sunset'],
    days: [
      [1, 'Arrive in Manhattan', 'Hotel check-in and Times Square after dark.', '', '', 'Hotel', ''],
      [2, 'Central Park and museums', 'Bike tour and the Met.', '3 hrs', '', 'Hotel', 'Breakfast'],
      [3, 'Downtown and Brooklyn', 'Statue of Liberty ferry, 9/11 Memorial and Brooklyn Bridge.', '4 hrs', '', 'Hotel', 'Breakfast'],
      [4, 'Village food walk and Broadway', 'Tastings in Greenwich Village and an evening show.', '3 hrs', '', 'Hotel', 'B · L'],
      [5, 'Departure', 'High Line stroll before your transfer.', '', '', '', 'Breakfast'],
    ],
    included: [['Four nights Midtown hotel', 'hotel'], ['Broadway tickets', 'ticket'], ['Bike tour and ferry', 'bike']],
    excluded: [['ESTA / US visa', 'file-text'], ['International flights', 'plane']],
    departures: [['2026-10-29', 14, 9], ['2026-12-10', 14, 14]],
  },
  {
    title: 'Grand Canyon & Arizona Road Trip',
    slug: 'grand-canyon-arizona-road-trip',
    country: 'usa',
    location: 'Arizona & Utah',
    summary: 'Sunrise at the Grand Canyon rim, Horseshoe Bend, Antelope Canyon and red-rock hikes in Sedona.',
    overview:
      'A road trip through the American Southwest’s most photogenic landscapes, with guided hikes, a Navajo-led slot canyon tour and nights at lodges near the rim.',
    priceFrom: 1380, durationDays: 6, difficulty: 'Moderate', groupSizeMax: 10, maxAltitude: 2280, bestSeason: 'March–May, Sept–Nov',
    rating: 4.8, reviewCount: 26, isFeatured: false, activities: ['trekking', 'sunrise'],
    photos: [
      ['1531694611353-d4758f86fa6d', 'Horseshoe Bend on the Colorado River'],
      ['1623300973992-54b05851941d', 'The Grand Canyon from a distance'],
      ['1535515505622-7621ebc4fc58', 'Hikers in a slot canyon'],
      ['1706387631343-79e1a2ec3fdb', 'A hiker overlooking a canyon'],
      ['1501258338179-b25f87809429', 'Sandstone arches under a blue sky'],
    ],
    highlights: ['Sunrise at Mather Point', 'Antelope Canyon with a Navajo guide', 'Sedona red-rock hike'],
    days: [
      [1, 'Phoenix to Sedona', 'Drive into red-rock country.', '1 hr', '1,320 m', 'Lodge', 'Dinner'],
      [2, 'Sedona trails', 'Cathedral Rock hike and a jeep tour.', '4 hrs', '1,400 m', 'Lodge', 'Breakfast'],
      [3, 'Grand Canyon South Rim', 'Rim trail walk and sunset at Hopi Point.', '3 hrs', '2,100 m', 'Rim lodge', 'Breakfast'],
      [4, 'Sunrise and Bright Angel Trail', 'Dawn at Mather Point and a partial canyon descent.', '5 hrs', '2,280 m', 'Rim lodge', 'Breakfast'],
      [5, 'Page: Antelope Canyon & Horseshoe Bend', 'Slot canyon light beams and the famous river bend.', '3 hrs', '1,300 m', 'Hotel', 'Breakfast'],
      [6, 'Return and departure', 'Drive back via Monument Valley viewpoints.', '', '', '', 'Breakfast'],
    ],
    included: [['Guided road trip in a small group van', 'car'], ['Five nights lodges', 'hotel'], ['Park passes and Antelope Canyon tour', 'ticket']],
    excluded: [['Flights to Phoenix', 'plane'], ['Most meals', 'utensils']],
    departures: [['2026-10-08', 10, 4], ['2027-04-01', 10, 10]],
  },
  {
    title: 'Sydney Harbour & Reef Explorer',
    slug: 'sydney-harbour-reef-explorer',
    country: 'australia',
    location: 'Sydney · Cairns',
    summary: 'Harbour ferries, Bondi coastal walks and two days snorkelling the Great Barrier Reef.',
    overview:
      'Start in Sydney with the Opera House, harbour ferries and the Bondi to Coogee clifftop walk, then fly north to Cairns for reef days on the outer Great Barrier Reef and a rainforest skyrail.',
    priceFrom: 2100, durationDays: 7, difficulty: 'Easy', groupSizeMax: 12, bestSeason: 'September–November',
    rating: 4.7, reviewCount: 21, isFeatured: false, activities: ['swimming', 'diving', 'city-breaks'],
    photos: [
      ['1590716209211-ea74d5f63573', 'Sydney Opera House and skyline at golden hour'],
      ['1549180030-48bf079fb38a', 'Sydney Opera House across the water'],
      ['1494948141550-221698c089c2', 'The Sydney Opera House sails'],
      ['1559651868-066bcc28f358', 'Visitors at the Opera House'],
    ],
    highlights: ['Opera House backstage tour', 'Bondi to Coogee coastal walk', 'Outer Great Barrier Reef snorkelling'],
    days: [
      [1, 'Arrive in Sydney', 'Harbour-view hotel and Circular Quay stroll.', '', '', 'Hotel', ''],
      [2, 'Opera House and harbour', 'Backstage tour, Rocks district and a ferry to Manly.', '3 hrs', '', 'Hotel', 'Breakfast'],
      [3, 'Bondi to Coogee', 'Clifftop walk, ocean pools and fish and chips.', '3 hrs', '', 'Hotel', 'Breakfast'],
      [4, 'Fly to Cairns', 'Esplanade lagoon swim and night market.', '', '', 'Hotel', 'Breakfast'],
      [5, 'Great Barrier Reef', 'Catamaran to the outer reef for snorkelling or an intro dive.', '', '', 'Hotel', 'B · L'],
      [6, 'Kuranda rainforest', 'Scenic railway up, skyrail down.', '2 hrs', '', 'Hotel', 'Breakfast'],
      [7, 'Departure', 'Transfer to Cairns airport.', '', '', '', 'Breakfast'],
    ],
    included: [['Six nights hotels', 'hotel'], ['Sydney–Cairns flight', 'plane'], ['Reef cruise with snorkel gear', 'fish'], ['Opera House tour', 'ticket']],
    excluded: [['Australian ETA / visa', 'file-text'], ['International flights', 'plane']],
    departures: [['2026-10-17', 12, 12], ['2026-11-21', 12, 6]],
  },
];

export const worldTrips = trips.map((t) => ({
  ...t,
  faq: worldFaq,
  photos: t.photos.map(([id, alt]) => [u(id), alt]),
})) as unknown as SeedTrip[];
