import { u } from './taxonomy';
import type { SeedTrip } from './types';

const nepalFaq = [
  { q: 'How fit do I need to be?', a: 'If you can walk 5–6 hours a day with a light daypack, you can do this. We build in acclimatisation days and set a pace that suits the group.' },
  { q: 'What about altitude sickness?', a: 'Our guides are trained in altitude first aid, carry oximeters and follow the “climb high, sleep low” rule. Your safety always comes before the itinerary.' },
  { q: 'Do I need travel insurance?', a: 'Yes. Your policy must cover trekking up to the maximum altitude of the trip and emergency helicopter evacuation.' },
  { q: 'Can the trip be private or customised?', a: 'Absolutely. Any departure can be made private, and we can add rest days, upgrade lodges or extend your stay.' },
];

export const nepalTrips: SeedTrip[] = [
  {
    title: 'Everest Base Camp Trek',
    slug: 'everest-base-camp-trek',
    country: 'nepal',
    location: 'Solukhumbu',
    summary: 'Walk in the footsteps of legends to the foot of the world’s highest mountain, through Sherpa villages, monasteries and glacier valleys.',
    overview:
      'The classic Himalayan journey. After a thrilling flight into Lukla you follow the Dudh Koshi valley to Namche Bazaar, the trading heart of the Khumbu, then climb slowly past Tengboche Monastery to the moraine of the Khumbu Glacier.\n\nWith two acclimatisation days, experienced Sherpa guides and cosy teahouses every night, the trek is paced for enjoyment as much as achievement. The reward: standing at Everest Base Camp and watching sunrise paint Everest gold from Kala Patthar.',
    priceFrom: 1450,
    durationDays: 14,
    difficulty: 'Challenging',
    groupSizeMax: 12,
    maxAltitude: 5545,
    bestSeason: 'Mar–May, Sep–Nov',
    rating: 4.9,
    reviewCount: 128,
    badge: 'Best seller',
    isFeatured: true,
    activities: ['trekking', 'sunrise', 'cultural', 'mountaineering'],
    photos: [
      ['1755621089875-946937e8b609', 'Kantega and Thamserku above prayer flags in the Everest region'],
      ['1693717671076-374d59bc2ff2', 'Everest Base Camp marker stone'],
      ['1701255136052-b33f78a886a4', 'Trekkers below Ama Dablam near Pheriche'],
      ['1700556581873-087bde7919a0', 'A Sherpa prayer ritual at a stupa on the trail'],
      ['1697746149225-63a33bcb2ea4', 'Tents at Gorak Shep before Base Camp'],
      ['1724341754508-f19ee59541bd', 'A trekker celebrating on a Himalayan summit'],
    ],
    highlights: [
      'Scenic mountain flight to Lukla and back',
      'Two acclimatisation days in Namche Bazaar and Dingboche',
      'Blessings at Tengboche Monastery',
      'Stand at Everest Base Camp (5,364 m)',
      'Sunrise over Everest from Kala Patthar (5,545 m)',
    ],
    days: [
      [1, 'Arrive in Kathmandu', 'Airport welcome and transfer to your hotel in Thamel. Evening trip briefing and kit check with your trek leader.', '', '1,400 m', 'Hotel', 'Dinner'],
      [2, 'Fly to Lukla, trek to Phakding', 'Early flight into the mountains, then an easy first walk along the Dudh Koshi river through pine forest.', '3–4 hrs', '2,610 m', 'Teahouse', 'B · L · D'],
      [3, 'Trek to Namche Bazaar', 'Cross the famous Hillary suspension bridge and climb to the horseshoe-shaped Sherpa capital. First views of Everest.', '6 hrs', '3,440 m', 'Teahouse', 'B · L · D'],
      [4, 'Namche Bazaar acclimatisation', 'Rest day with a short hike to the Everest View Hotel. The afternoon is free for the Sherpa museum and the local market.', '4 hrs', '3,440 m', 'Teahouse', 'B · L · D'],
      [5, 'Trek to Tengboche', 'Contour high above the valley with Ama Dablam ahead, then climb to Tengboche Monastery for evening prayers.', '5 hrs', '3,860 m', 'Teahouse', 'B · L · D'],
      [6, 'Trek to Dingboche', 'Leave the tree line behind as the valley opens into stone-walled potato fields beneath Island Peak.', '5–6 hrs', '4,410 m', 'Teahouse', 'B · L · D'],
      [7, 'Dingboche acclimatisation', 'Hike up Nangkartshang ridge for views of Makalu, then rest and hydrate for the days ahead.', '3–4 hrs', '4,410 m', 'Teahouse', 'B · L · D'],
      [8, 'Trek to Lobuche', 'Pass the climbers’ memorials at Thukla and follow the lateral moraine of the Khumbu Glacier.', '5 hrs', '4,910 m', 'Teahouse', 'B · L · D'],
      [9, 'Gorak Shep and Everest Base Camp', 'The big day. Drop bags at Gorak Shep, then walk the glacier edge to Base Camp and its famous boulder.', '7–8 hrs', '5,364 m', 'Teahouse', 'B · L · D'],
      [10, 'Kala Patthar sunrise, descend to Pheriche', 'A pre-dawn climb for the best view of Everest on the trek, then a long, happy descent.', '7 hrs', '5,545 m', 'Teahouse', 'B · L · D'],
      [11, 'Trek to Namche Bazaar', 'Retrace the valley with thicker air and lighter legs. Celebrate with a bakery stop in Namche.', '6–7 hrs', '3,440 m', 'Teahouse', 'B · L · D'],
      [12, 'Trek to Lukla', 'The final walking day, finishing with a thank-you evening for the porters and guides.', '6–7 hrs', '2,860 m', 'Teahouse', 'B · L · D'],
      [13, 'Fly to Kathmandu', 'Morning flight back to the city. Free afternoon and farewell dinner with a cultural show.', '', '1,400 m', 'Hotel', 'B · D'],
      [14, 'Departure', 'Transfer to the airport for your onward flight — or ask us to add a Chitwan safari.', '', '1,400 m', '', 'Breakfast'],
    ],
    included: [
      ['Airport pick-up and drop-off', 'car'],
      ['Kathmandu–Lukla return flights', 'plane'],
      ['Licensed English-speaking trek leader', 'user-check'],
      ['Porter support (1 porter for 2 trekkers)', 'backpack'],
      ['Teahouse accommodation and all meals on trek', 'bed'],
      ['Sagarmatha National Park and local permits', 'shield-check'],
      ['Emergency oxygen and first-aid kit', 'heart-pulse'],
    ],
    excluded: [
      ['International flights and Nepal visa', 'plane'],
      ['Travel insurance with helicopter evacuation', 'shield'],
      ['Tips for guides and porters', 'hand-coins'],
    ],
    faq: nepalFaq,
    packing: ['Broken-in waterproof hiking boots', 'Down jacket and warm layers', 'Sleeping bag rated to −10 °C', 'Trekking poles', 'Refillable water bottles and purification tablets', 'Sunglasses, sunscreen and a sun hat'],
    departures: [['2026-10-12', 12, 3], ['2026-11-02', 12, 8], ['2027-03-22', 12, 12], ['2027-04-12', 12, 10, 1590]],
  },
  {
    title: 'Annapurna Base Camp Trek',
    slug: 'annapurna-base-camp-trek',
    country: 'nepal',
    location: 'Kaski',
    summary: 'A spectacular walk into a natural amphitheatre ringed by Annapurna I, Machhapuchhre and a crown of seven-thousanders.',
    overview:
      'From the lakeside town of Pokhara, this trek climbs through Gurung villages, rhododendron forest and bamboo groves into the Annapurna Sanctuary. Hot springs at Jhinu Danda soothe tired legs on the way down, and sunrise at Poon Hill is an optional bonus.',
    priceFrom: 1090,
    durationDays: 11,
    difficulty: 'Moderate',
    groupSizeMax: 12,
    maxAltitude: 4130,
    bestSeason: 'Mar–May, Oct–Dec',
    rating: 4.8,
    reviewCount: 96,
    isFeatured: true,
    activities: ['trekking', 'sunrise', 'cultural'],
    photos: [
      ['1572109801525-0bb0272e8579', 'Villagers working below the Annapurna range'],
      ['1685353259900-85286668a8f2', 'Snow-capped Annapurna peak under cloud'],
      ['1665849865197-6b4f0d1206e1', 'The Annapurna mountain range'],
      ['1592623171049-4be9e0f5a501', 'Forested ridges on the way to the sanctuary'],
      ['1619796696652-a29a854f21a0', 'Himalayan silhouettes at dusk'],
    ],
    highlights: ['Sunrise over the Annapurnas from the sanctuary', 'Gurung culture in Ghandruk and Chhomrong', 'Natural hot springs at Jhinu Danda', 'Two nights by Phewa Lake in Pokhara'],
    days: [
      [1, 'Kathmandu to Pokhara', 'Scenic drive or short flight to Pokhara. Sunset stroll along Phewa Lake.', '', '822 m', 'Lakeside hotel', 'Dinner'],
      [2, 'Drive to Nayapul, trek to Ghandruk', 'Climb stone steps to a beautiful Gurung village with a museum of local life.', '5 hrs', '1,940 m', 'Teahouse', 'B · L · D'],
      [3, 'Trek to Chhomrong', 'Terraced hillsides and the first close views of Machhapuchhre, the “fishtail” mountain.', '6 hrs', '2,170 m', 'Teahouse', 'B · L · D'],
      [4, 'Trek to Dovan', 'Into cool bamboo and rhododendron forest along the Modi Khola river.', '6 hrs', '2,600 m', 'Teahouse', 'B · L · D'],
      [5, 'Trek to Machhapuchhre Base Camp', 'The valley narrows between towering walls before opening into the sanctuary.', '5 hrs', '3,700 m', 'Teahouse', 'B · L · D'],
      [6, 'Annapurna Base Camp, return to Bamboo', 'Dawn walk to ABC for sunrise on Annapurna I, then descend to thicker air.', '8 hrs', '4,130 m', 'Teahouse', 'B · L · D'],
      [7, 'Trek to Jhinu Danda hot springs', 'Downhill to riverside pools — the best reward on any trek.', '6 hrs', '1,780 m', 'Teahouse', 'B · L · D'],
      [8, 'Trek out and drive to Pokhara', 'Final walk to the road head and an evening back by the lake.', '4 hrs', '822 m', 'Lakeside hotel', 'B · D'],
      [9, 'Pokhara free day', 'Optional paragliding, boating to Tal Barahi temple or a sunrise at Sarangkot.', '', '822 m', 'Lakeside hotel', 'Breakfast'],
      [10, 'Return to Kathmandu', 'Drive or fly back to the capital for a farewell dinner.', '', '1,400 m', 'Hotel', 'B · D'],
      [11, 'Departure', 'Airport transfer for your onward journey.', '', '1,400 m', '', 'Breakfast'],
    ],
    included: [
      ['All ground transport as listed', 'bus'],
      ['Licensed trek leader and porters', 'user-check'],
      ['Teahouse stays and meals on trek', 'bed'],
      ['ACAP permit and TIMS card', 'shield-check'],
      ['Two nights lakeside in Pokhara', 'hotel'],
    ],
    excluded: [['International flights and visa', 'plane'], ['Travel insurance', 'shield'], ['Optional activities in Pokhara', 'wind']],
    faq: nepalFaq,
    departures: [['2026-10-05', 12, 6], ['2026-11-09', 12, 11], ['2027-03-15', 12, 12]],
  },
  {
    title: 'Pokhara Family Escape',
    slug: 'pokhara-family-escape',
    country: 'nepal',
    location: 'Pokhara',
    summary: 'Sunrise at Sarangkot, boating on Phewa Lake, paragliding and waterfalls — the relaxed Nepal family holiday our guests love most.',
    overview:
      'Pokhara is Nepal at its most easy-going: a lakeside town under the Annapurnas with gentle walks, adventure activities for every age and excellent food. This short break mixes calm mornings with a little adrenaline — Kusma’s giant swing is optional!',
    priceFrom: 634,
    durationDays: 5,
    difficulty: 'Easy',
    groupSizeMax: 16,
    maxAltitude: 1600,
    bestSeason: 'Year-round (best Oct–Apr)',
    rating: 4.9,
    reviewCount: 74,
    badge: 'Family favourite',
    isFeatured: true,
    activities: ['sunrise', 'paragliding', 'swimming', 'cultural'],
    photos: [
      ['1735533441842-33c5e47b22ae', 'Colourful boats on Phewa Lake, Pokhara'],
      ['1610997686651-98492fd08108', 'Paragliders above Phewa Lake'],
      ['1706323625285-648bb6825e03', 'Mountains reflected in Phewa Lake'],
      ['1729942500273-da9f330a51a9', 'A wooden boat on the shore of the lake'],
      ['1746280484973-b5359505f5d1', 'Snowy peaks lit pink at sunrise'],
    ],
    highlights: ['Sunrise over the Annapurnas from Sarangkot', 'Boat ride to Tal Barahi island temple', 'Tandem paragliding (optional)', 'World Peace Pagoda and Davis Falls'],
    days: [
      [1, 'Arrive in Pokhara', 'Transfer to your lakeside hotel and an evening boat ride as the sun sets.', '', '822 m', 'Lakeside hotel', 'Dinner'],
      [2, 'Sarangkot sunrise and city sights', 'Early drive to Sarangkot for sunrise, then Davis Falls, Gupteshwor Cave and the World Peace Pagoda.', '2 hrs', '1,600 m', 'Lakeside hotel', 'B · D'],
      [3, 'Adventure day', 'Choose tandem paragliding, zip-lining or the Kusma bungee and swing — or a gentle village walk.', '', '822 m', 'Lakeside hotel', 'Breakfast'],
      [4, 'Begnas Lake and local food', 'A quieter lake, a cooking class with a local family and time to shop for souvenirs.', '2 hrs', '650 m', 'Lakeside hotel', 'B · L'],
      [5, 'Departure', 'Transfer to Pokhara airport or bus park.', '', '822 m', '', 'Breakfast'],
    ],
    included: [['Private transport in Pokhara', 'car'], ['Four nights lakeside hotel', 'hotel'], ['Sightseeing entry fees', 'ticket'], ['Local English-speaking guide', 'user-check'], ['Sunset boat ride', 'sailboat']],
    excluded: [['Paragliding and bungee fees', 'wind'], ['Flights to Pokhara', 'plane'], ['Lunches unless stated', 'utensils']],
    faq: [
      { q: 'Is this trip suitable for young children?', a: 'Yes — all walks are short and activities are optional. Tell us your children’s ages and we will tailor the plan.' },
      { q: 'How safe is paragliding?', a: 'We only work with licensed operators and experienced tandem pilots with full safety equipment.' },
    ],
    departures: [['2026-10-18', 16, 9], ['2026-12-26', 16, 4], ['2027-02-14', 16, 16]],
  },
  {
    title: 'Kathmandu Valley Heritage Tour',
    slug: 'kathmandu-valley-heritage-tour',
    country: 'nepal',
    location: 'Kathmandu Valley',
    summary: 'Seven UNESCO World Heritage monuments in four days — living temples, royal squares and the great stupa of Boudhanath.',
    overview:
      'The Kathmandu Valley holds an astonishing concentration of art and architecture. With a local historian as your guide you will explore the Durbar Squares of Kathmandu, Patan and Bhaktapur, join pilgrims circling Boudhanath at dusk and watch evening aarti at Pashupatinath.',
    priceFrom: 480,
    durationDays: 4,
    difficulty: 'Easy',
    groupSizeMax: 14,
    maxAltitude: 1400,
    bestSeason: 'Year-round',
    rating: 4.7,
    reviewCount: 58,
    isFeatured: false,
    activities: ['cultural', 'pilgrimage', 'city-breaks'],
    photos: [
      ['1731052368947-9f262c4e9f4c', 'Kathmandu Durbar Square in the evening'],
      ['1699202700754-1e5cbf0f8660', 'Boudhanath Stupa with prayer flags'],
      ['1618851142562-ff30d09313a9', 'Bhaktapur Durbar Square'],
      ['1663060010422-a4b846aa1037', 'Dattatreya Temple in Bhaktapur'],
      ['1665394183024-7a95b156d427', 'Temple statues in the Kathmandu Valley'],
    ],
    highlights: ['Swayambhunath “Monkey Temple” at sunrise', 'Evening aarti at Pashupatinath', 'Kora around Boudhanath Stupa', 'Pottery square and juju dhau yoghurt in Bhaktapur'],
    days: [
      [1, 'Arrive and Swayambhunath', 'Airport welcome, then climb to the hilltop stupa for views over the city.', '1 hr', '1,400 m', 'Heritage hotel', 'Dinner'],
      [2, 'Kathmandu Durbar Square and Patan', 'Royal palaces, the Kumari’s house and the finest metalwork museum in South Asia.', '3 hrs', '1,400 m', 'Heritage hotel', 'Breakfast'],
      [3, 'Bhaktapur, Boudhanath and Pashupatinath', 'A medieval city in the morning, the great stupa in the afternoon and riverside aarti at dusk.', '3 hrs', '1,400 m', 'Heritage hotel', 'B · D'],
      [4, 'Departure', 'Free morning for shopping in Thamel before your transfer.', '', '1,400 m', '', 'Breakfast'],
    ],
    included: [['Heritage hotel with breakfast', 'hotel'], ['Private guide and vehicle', 'car'], ['All monument entry fees', 'ticket'], ['Welcome and farewell dinners', 'utensils']],
    excluded: [['International flights and visa', 'plane'], ['Personal expenses', 'wallet']],
    departures: [['2026-09-28', 14, 7], ['2026-10-26', 14, 14], ['2026-11-23', 14, 12]],
  },
  {
    title: 'Chitwan Jungle Safari',
    slug: 'chitwan-jungle-safari',
    country: 'nepal',
    location: 'Chitwan National Park',
    summary: 'Track one-horned rhinos by jeep and canoe in Nepal’s lowland jungle, with Tharu culture and elephant-free conservation visits.',
    overview:
      'Chitwan is one of Asia’s great wildlife parks. Naturalist guides lead jeep drives, dugout canoe trips and jungle walks in search of rhinos, gharial crocodiles, deer and — with luck — a Bengal tiger. Evenings bring Tharu dance and village walks.',
    priceFrom: 390,
    durationDays: 3,
    difficulty: 'Easy',
    groupSizeMax: 12,
    bestSeason: 'October–March',
    rating: 4.6,
    reviewCount: 41,
    isFeatured: false,
    activities: ['wildlife-safari', 'cultural'],
    photos: [
      ['1751931817996-368c9ee352ee', 'A one-horned rhino beside a safari jeep in Chitwan'],
      ['1534215782964-d58601aa091c', 'Rhinoceros in tall grass'],
      ['1754492064752-f440ea2a460b', 'An elephant bathing in the river'],
      ['1740979071064-b86791d26639', 'Wildlife in the Chitwan grasslands'],
      ['1549888668-19281758dfbe', 'Jungle landscape in the Terai'],
    ],
    highlights: ['Half-day jeep safari in the national park', 'Dugout canoe on the Rapti River', 'Tharu village walk and cultural show'],
    days: [
      [1, 'Arrive in Sauraha', 'Check in to your jungle lodge, sunset by the Rapti River and a Tharu cultural evening.', '1 hr', '150 m', 'Jungle lodge', 'L · D'],
      [2, 'Canoe and jeep safari', 'Morning canoe trip, jungle walk to the crocodile breeding centre and an afternoon jeep safari.', '6 hrs', '150 m', 'Jungle lodge', 'B · L · D'],
      [3, 'Bird walk and departure', 'Early bird-watching walk before transferring onward.', '2 hrs', '150 m', '', 'Breakfast'],
    ],
    included: [['Jungle lodge full board', 'bed'], ['National park fees', 'shield-check'], ['Naturalist guide', 'binoculars'], ['Jeep and canoe safaris', 'car']],
    excluded: [['Transport to Chitwan', 'bus'], ['Drinks', 'coffee']],
    departures: [['2026-10-10', 12, 5], ['2026-11-14', 12, 12], ['2027-01-09', 12, 9]],
  },
  {
    title: 'Trishuli River Rafting Adventure',
    slug: 'trishuli-river-rafting',
    country: 'nepal',
    location: 'Trishuli River',
    summary: 'Grade III white water, riverside camping and swimming stops on Nepal’s favourite first rafting river.',
    overview:
      'Just a few hours from Kathmandu, the Trishuli offers exciting but friendly rapids through deep gorges and small villages. Certified river guides and safety kayakers run every trip; nights are spent at a sandy riverside camp.',
    priceFrom: 180,
    durationDays: 2,
    difficulty: 'Moderate',
    groupSizeMax: 16,
    bestSeason: 'Sep–Nov, Mar–May',
    rating: 4.7,
    reviewCount: 33,
    isFeatured: false,
    activities: ['rafting', 'swimming'],
    photos: [
      ['1641584495089-5914d85d9bcc', 'Rafting the Trishuli River in Nepal'],
      ['1692095296859-60427614df87', 'A yellow raft running a rapid'],
      ['1658355686821-f412c8397a0d', 'A raft crew paddling in unison'],
      ['1629248564797-8c5ba85da9d3', 'Paddlers on a sunny river day'],
    ],
    highlights: ['Grade III rapids with certified guides', 'Riverside camp with bonfire dinner', 'Swimming and cliff-jump stops'],
    days: [
      [1, 'Kathmandu to Charaudi, rafting day one', 'Safety briefing and a full afternoon of rapids before camp on a white-sand beach.', '4 hrs rafting', '', 'Riverside camp', 'L · D'],
      [2, 'Rafting day two and return', 'More rapids and swim stops, then lunch and the drive back to Kathmandu or on to Pokhara.', '3 hrs rafting', '', '', 'B · L'],
    ],
    included: [['Rafting equipment and safety kayaker', 'life-buoy'], ['Riverside camping and meals', 'tent'], ['Return transport', 'bus']],
    excluded: [['Personal travel insurance', 'shield'], ['Drinks at camp', 'coffee']],
    departures: [['2026-10-03', 16, 10], ['2026-10-24', 16, 2], ['2026-11-07', 16, 16]],
  },
  {
    title: 'Kathmandu to Pokhara Mountain Bike Ride',
    slug: 'kathmandu-pokhara-mountain-bike',
    country: 'nepal',
    location: 'Middle Hills',
    summary: 'Seven days of singletrack, ridge roads and village trails linking Nepal’s two favourite cities, with a support jeep all the way.',
    overview:
      'Ride out of the Kathmandu Valley over Chandragiri pass, through hill towns like Bandipur and down forest trails to the Seti river before a triumphant final day along Phewa Lake. Quality hardtail bikes, a mechanic and a vehicle for tired legs are all included.',
    priceFrom: 890,
    durationDays: 7,
    difficulty: 'Challenging',
    groupSizeMax: 10,
    maxAltitude: 2520,
    bestSeason: 'Oct–Dec, Feb–Apr',
    rating: 4.8,
    reviewCount: 19,
    isFeatured: false,
    activities: ['cycling', 'cultural', 'sunrise'],
    photos: [
      ['1571330176922-871ca5bd015b', 'A mountain bike at Mardi Base Camp above Pokhara'],
      ['1511994298241-608e28f14fde', 'An off-road bicycle on a hill'],
      ['1629056528325-f328b5f27ae7', 'Riders on a mountain trail'],
      ['1535369643553-a33e0d1ac81d', 'Riding through the forest'],
    ],
    highlights: ['Chandragiri ridge with a Himalayan panorama', 'Overnight in hilltop Bandipur', 'Mechanic and support jeep throughout'],
    days: [
      [1, 'Kathmandu warm-up ride', 'Bike fitting and a loop to Shivapuri National Park.', '3 hrs', '1,900 m', 'Hotel', 'Dinner'],
      [2, 'Over Chandragiri to Daman', 'A big climb rewarded by one of the widest mountain views in Nepal.', '6 hrs', '2,520 m', 'Mountain lodge', 'B · L · D'],
      [3, 'Descent to Palung and Hetauda road', 'Long, flowing downhill through orange orchards.', '5 hrs', '1,750 m', 'Guesthouse', 'B · L · D'],
      [4, 'Ride to Bandipur', 'Village trails and a steep finish to a perfectly preserved Newar hill town.', '6 hrs', '1,030 m', 'Heritage lodge', 'B · L · D'],
      [5, 'Bandipur to Dumre and the Seti river', 'Early sunrise at Tundikhel, then riverside tracks.', '5 hrs', '450 m', 'Riverside lodge', 'B · L · D'],
      [6, 'Final push to Pokhara', 'Ridge trails and a celebratory spin along Phewa Lake.', '6 hrs', '822 m', 'Lakeside hotel', 'B · L · D'],
      [7, 'Departure from Pokhara', 'Rest, pack up and transfer.', '', '822 m', '', 'Breakfast'],
    ],
    included: [['Hardtail mountain bike and helmet', 'bike'], ['Ride leader and mechanic', 'wrench'], ['Support jeep', 'car'], ['All accommodation and meals on the ride', 'bed']],
    excluded: [['Riding shoes and pedals', 'footprints'], ['Travel insurance', 'shield']],
    departures: [['2026-11-01', 10, 6], ['2027-02-21', 10, 10]],
  },
].map((t) => ({ ...t, photos: t.photos.map(([id, alt]) => [u(id), alt]) })) as SeedTrip[];
